### ISSUE TITLE
Benchmark import times

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy_benchmarks#14]
We just had a complaint on the SymPy mailing list about rising import times.

**Comment by moorepants** [comment]
The complaint came from importing sympy on a smart phone which takes ~10 seconds. This is significantly longer than it takes to import on my laptop ~0.5s.

**Comment by aktech** [comment]
BTW, which mobile OS does that?

**Comment by aktech** [comment]
Ok, got it [here](https://groups.google.com/forum/#!topic/sympy/H8uAInEheIQ)

**Comment by bjodah** [comment]
We need to figure out if `asv` imports the benchmarked project earlier than the first import statement in any benchmarks. If it doesn't we should be able to make a simple benchmark for it (given it is run first...).

**Comment by moorepants** [comment]
I tried it and it seems like the module is imported previous to the actual benchmark run. It takes about 0.5s for a cold import on my machine and when I try to build a benchmark around the import it reports something in the microseconds. Not sure how to fix it yet...

**Comment by bjodah** [comment]
In that case maybe we should patch `asv` to gather import times and make that data (optionally) available, maybe as a config file option? e.g. `"benchmark_import": false`, that data will essentially be gathered for free

**Comment by bjodah** [comment]
Since it looks as if whole SymPy was recompiled on each import:

https://groups.google.com/forum/#!topic/sympy/H8uAInEheIQ

I am closing this issue for now. Feel free to reopen if the issue reappears.
